name:                hlambda
version:             0.1.0.0
github:              "githubuser/hlambda"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hlambda#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - array
  - prettyprinter
  - text
  - prettyprinter-ansi-terminal
  - mtl
  - containers
  - parsec

executables:
  hl:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hlambda
    - text 
    - haskeline
    - mtl
    - pretty-simple
    - prettyprinter
    - prettyprinter-ansi-terminal
    - filepath

tests:
  hlambda-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hlambda
    - HUnit
    - hspec
    - raw-strings-qq
