#!/usr/bin/env bash

interpreter_bin="target/debug/interpreter"

valgrind_tool=$1
shift

valgrind_args=""
interpreter_args=""
while [[ $# -gt 0 ]]; do
  if [[ $1 != "--" ]]; then
    valgrind_args="$valgrind_args $1"
    shift
  else
    shift
    interpreter_args="$@"
    break
  fi
done


if [[ $valgrind_tool = 'memcheck' ]]; then
  shift
  valgrind --tool=memcheck --leak-check=yes --show-reachable=yes --num-callers=20 --track-fds=yes $valgrind_args $interpreter_bin $interpreter_args
elif [[ $valgrind_tool = 'massif' ]]; then
  if [[ ! -d 'massif' ]]; then
    mkdir "massif"
  fi

  shift
  valgrind --tool=massif --massif-out-file="massif/massif.out.%p" --heap=yes --stacks=yes --time-unit=B $valgrind_args $interpreter_bin $interpreter_args
else
  echo "usage: ./run-valgrind <memcheck|massif> [valgrind-args..] -- [interpreter-args..]"
fi

